Regions:
  coal_mine:
    settings:
      PreventBuilding: true
      DisableVanillaDrops: false
    blocks:
      COAL_ORE:
        delay: 60
        replacement: STONE
        regeneration:
          COAL_ORE: 100
      STONE:
        delay: 60
        replacement: COBBLESTONE
        regeneration:
          STONE: 100
      COBBLESTONE:
        delay: 60
        replacement: BEDROCK
        regeneration:
          COBBLESTONE: 100